### ISSUE TITLE
Placeholder translation

### ISSUE THREAD

**Issue by samacs** [Emagister/zend-form-decorators-bootstrap#12]
I don't know if it is beyond the scope of this implementation or if this is the right place to point this out, but I think would be nice if placeholders could be translated.

As they're nothing more than an attribute perhaps and if statement would do the job (I don't know where to apply it) but seems like a messy solution.

To workaround this I just called the `getView()` method and use translator helper from the view.

**Comment by theUniC** [comment]
Currently, this is not supported. As of the "placeholder" attribute has no special treatment a dedicated Decorator will be needed in order to achieve the translation.
