### ISSUE TITLE
Zend_SubForm

### ISSUE THREAD

**Issue by tomiford** [Emagister/zend-form-decorators-bootstrap#15]
Does this extension work with Zend_SubForm. I can't see any mention of it in the code?

**Comment by theUniC** [comment]
No. At the moment, there is no explicit support for `Zend_Form_Subform`. But as of `Zend_Form::addSubform` accepts a `Zend_Form` instance as a first parameter, you can pass a `Twitter_Bootstrap_Form` instance to the `Zend_Form::addSubform` method. It has not been tested, but I figure out that won't be tricky to adapt the decorators to the `Zend_Form_Subform`.
