### ISSUE TITLE
Hidden elements decorators

### ISSUE THREAD

**Issue by adepretis** [Emagister/zend-form-decorators-bootstrap#2]
There's a slight problem with decorators for hidden elements: because `Zend_Form::__construct()` calls `$this->init()` and `Twitter_Bootstrap_Form_*` calls `$this->setElementDecorators(...)` after `parent::__construct()` it is not possible to remove bootstrap decorators from hidden elements.

Unless of course by overloading `Zend_Form::render()` ... but maybe this can be avoided

**Comment by theUniC** [comment]
I think it's the same case of the PR you made before. We're going to move all the `parent::__construct` in order to allow adding custom decorators at the `Zend_Form::init` method.

Regards,
Christian.

**Comment by theUniC** [comment]
All the `parent::__construct` calls on the forms have been moved to the bottom of the constructor body. Now, custom decorators can be added using `Zend_Form::init` method.

Regards,
Christian.
