### ISSUE TITLE
Add support for labels in prepend/append

### ISSUE THREAD

**Issue by syphernl** [Emagister/zend-form-decorators-bootstrap#24]
The normal Bootstrap classes contain labels above or next to the input fields. 
This script appears to be ignoring the label setting, and refuses to show them.

**Comment by syphernl** [comment]
FWIW this is working fine when using `createElement` + `addElement` but not when you provide a label to `addElement` directly.

**Comment by syphernl** [comment]
Hmm apparantly its due to prepend/append, but this is supposed to work according to the Bootstrap documentation.

**Comment by lrobert** [comment]
Can you attach an example? I'd love to have a look at the issue.

**Comment by theUniC** [comment]
Closing for now, as no code example provided to reproduce the issue. Will reopen when needed.

**Comment by ilyeah** [comment]
how to realize this in horizontal form?

``` html
<div class="control-group">
    <div class="controls">
      <label class="checkbox">
        <input type="checkbox"> Remember me
      </label>
    </div>
```
