### ISSUE TITLE
Space in markup causing gap between prepend value and text input

### ISSUE THREAD

**Issue by oller** [Emagister/zend-form-decorators-bootstrap#28]
With a prepended text input, there's a few pixel gap between the prefixed value and the text input itself.

I've diagnosed this as a markup issue, as there is a space/line break between those.  Removing this fixes the gap.

Looks like the addon decorator needs tweaking to resolve this?

This only occurs with prepend, append is fine.

Am using bootstrap 2.0.4

**Comment by willemo** [comment]
I'm having the same issue. A dirty way to resolve this with jQuery is by using this code:

``` javascript
$('.input-prepend').each(function(){
    var input = $(this);
    var children = $(this).children();
    $(this).html('');
    $.each(children, function(i, child) {
        input.append(child);
    });
});
```

This removes all elements from the input-prepend div and re-appends them without the whitespace.
It's a dirty fix, but it works for now.

**Comment by lrobert** [comment]
I've added a trim to the content when rendering the add-ons. Pull requested.
