### ISSUE TITLE
multicheckbox

### ISSUE THREAD

**Issue by chiru007** [Emagister/zend-form-decorators-bootstrap#33]
I am unable set checkboxes on form redisplay

->setValue(array)

is not working, no checkboxes are checked. I have debugged and found $value in Twitter_Bootstrap_View_Helper_FormMultiCheckbox  has got strange values.

but if I pass just one value instead of array it is working fine, one checkbox selected.

any ideas. please help

Thanks,

**Comment by theUniC** [comment]
Can you post some example code in order to reproduce the issue?

Thanks!

**Comment by chiru007** [comment]
thanks for your quick reply

its resolved now. stupid mistake.

isArray set to false
