### ISSUE TITLE
Horizontal form does not display items properly when using createElement

### ISSUE THREAD

**Issue by lrobert** [Emagister/zend-form-decorators-bootstrap#35]
In a Twitter_Bootstrap_Form_Horizontal if you add an element using the following code, the element will use zend decorators such as the DtDd tags.

``` php
$textElement = $this->createElement('text', 'myText', array(
    'label' => 'This is a label'
));

$this->addElement($textElement);
```

**Comment by lrobert** [comment]
This issue is still happening. The previous fix caused elements that do not need the ViewHelper decorator (such as File) to display twice.

**Comment by lrobert** [comment]
This seems to be an issue with createElement itself. It's supposed to copy the default decorators that we set, but it is not for some reason. There is a zend ticket about this. We should add more comments to have it resolved.

http://framework.zend.com/issues/browse/ZF-8942?page=com.atlassian.jira.plugin.system.issuetabpanels:changehistory-tabpanel

**Comment by theUniC** [comment]
This is related to a `Zend_Form` issue. Closing as this not applies to the library itself.
