### ISSUE TITLE
Can't create a submit element with an icon

### ISSUE THREAD

**Issue by clawfire** [Emagister/zend-form-decorators-bootstrap#45]
`Twitter_Bootstrap_Form_Element_Submit` didn't support icons but `Twitter_Bootstrap_Form_Element_Button` did. Also we can't make a Button type `submit`without getting the icon as a `value`in the generated code , resulting it passed as an element in the post / get call .

**Comment by lrobert** [comment]
You need to make a Button element and make it of the type 'submit'

``` php
<?php
// Inside the form init
$this->addElement('button', 'mySubmitName', array(
    'label' => 'Save',
    'icon' => 'plus-sign',
    'whiteIcon' => true,
    'type' => 'submit'
));

```

That will get you a submit button with the icon

**Comment by theUniC** [comment]
Exactly. As @lrobert points out with his example code, in order to get a button with a small icon inside you need to use a `Twitter_Bootstrap_Form_Element_Button`.

**Comment by clawfire** [comment]
I'll test that, it's make the type="submit" ok but place the `<i class="icon-plus-sign"></i>` into the value attribut, so it's passed with the form ...

**Comment by lrobert** [comment]
'ok but place the into the value attribut'

Place what into the value attribute?

**Comment by clawfire** [comment]
`<i class="icon-plus-sign"></i>`

**Comment by lrobert** [comment]
You can add that directly into the value by using 

``` php
// Inside the form init
$this->addElement('button', 'mySubmitName', array(
    'label' => 'Save',
    'icon' => 'plus-sign',
    'whiteIcon' => true,
    'type' => 'submit',
    'value' => 'Whatever you want here'
));
```

But I must ask, why would you want that posted?

**Comment by clawfire** [comment]
I don't want it, `<i class="icon-plus-sign"></i>` is automatically inserted into `value=""` because it's the label of the button :(

**Comment by lrobert** [comment]
Funny thing, I just ran into this! It doesn't even create the value properly :/

I'll open a new ticket describing the issue and I'll work on a fix.

**Comment by clawfire** [comment]
@lrobert thx you
