### ISSUE TITLE
FieldSize decorator: unfortunate attribute 'size'

### ISSUE THREAD

**Issue by adepretis** [Emagister/zend-form-decorators-bootstrap#5]
Hi,

the 'size' attribute is captured by the FieldSize decorator and "converted" to `class="span<size>"`. Because `size` is a valid attribute for `<select>` this clashes with use cases where a `Zend_Form_Element_Select` or `Zend_Form_Element_MultiSelect` should actually render as `<select size="5">`.

This is especially true for non-multiselect selects that should get a size (height) because it can't be set using CSS. For multiselects it's possible to use a CSS workaround like e.g. `height: 200px` - doesn't work for non-multiselect selects.

What would be the solution for this? - excluding `$element->getType() !== "Zend_Form_Element_Select"` in the FieldSize decorator? Adding another option like "height" for it (translating to `size`)? Or is this once again a case like issue #2 and the possibility to remove element decorators by moving `parent::__construct()`?

In that case I think I'd prefer the "height" option, because it saves some work when adding `Zend_Form_Element_Select` elements.

What's your opinion?

**Comment by theUniC** [comment]
Hi,

Thank you for notifying this issue. Sincerely, we didn't realized in the case of multi-select fields. I agree with you in that adding some kind of decision logic like `$element->getType() !== "Zend_Form_Element_Select"` would not be the best solution. So I think translating the `size` would be the point here.

But I think `height` does not fit in the conceptually intention of the FieldSize decorator, so I would prefer another name for the attribute. Something like `dimension` could play well with the decorator.

Have you got any other suggestion for the new name?

Thanks!
Regards,
Christian

**Comment by theUniC** [comment]
The FieldSize decorator, now uses the "dimension" attribute to set the size class.

``` php
<?php
class My_Bootstrap_Form extends Twitter_Bootstrap_Form_Horizontal
{
    public function init()
    {
        // Some text
        $this->addElement('text', 'input1', array(
            'label'       => 'E-mail',
            'dimension' => 5
        ));
    }
}
```

**Comment by adepretis** [comment]
That's great news, thanks for fixing this and sorry for not answering earlier!
