### ISSUE TITLE
File element decorator issue

### ISSUE THREAD

**Issue by perfection** [Emagister/zend-form-decorators-bootstrap#6]
First of all thanks for the great work.
<b>Warning</b>:  Exception caught by form: No file decorator found... unable to render file element
Stack Trace:
#0 C:\Program Files (x86)\Zend\www\imob3\www\library\Twitter\Bootstrap\Form\Decorator\FormElements.php(79): Zend_Form_Element_File->render()
#1 C:\Program Files (x86)\Zend\ZendServer\share\ZendFramework\library\Zend\Form\DisplayGroup.php(920): Twitter_Bootstrap_Form_Decorator_FormElements->render('')
#2 C:\Program Files (x86)\Zend\www\imob3\www\library\Twitter\Bootstrap\Form\Decorator\FormElements.php(79): Zend_Form_DisplayGroup->render()
#3 C:\Program Files (x86)\Zend\ZendServer\share\ZendFramework\library\Zend\Form.php(2904): Twitter_Bootstrap_Form_Decorator_FormElements->render('')
#4 C:\Program Files (x86)\Zend\ZendServer\share\ZendFramework\library\Zend\Form.php(2920): Zend_Form->render()
#5 C:\Program Files (x86)\Zend\www\imob3\www\application\modules\admin\views\scripts\agenti\add.phtml(1): Zend_Form->__toString()
#6 C:\Program Files (x86)\Zend\ZendServer\share\ZendFramework\library\Zend\View.php(108): inclu in <b>C:\Program Files (x86)\Zend\ZendServer\share\ZendFramework\library\Zend\Form.php</b> on line <b>2925</b><br />

config.ini

autoloaderNamespaces[] = "Twitter"

Everything else works.

**Comment by theUniC** [comment]
At a first glance, does not seem to be an error from the decorators. Can you paste the snippet of code that causes the error?

**Comment by perfection** [comment]
sure

<?php
class Form_AddAgent extends Twitter_Bootstrap_Form_Horizontal 
{
    public function init ()
    {

```
    $this->setMethod("post");



    $nume = new Zend_Form_Element_Text("nume");
    $nume->setLabel("Nume:")
        ->setDescription ("Introduceti Numele Agentului")
        ->setRequired(true);

    $prenume = new Zend_Form_Element_Text("prenume");
    $prenume->setLabel("Prenume:")
        ->setDescription ("Introduceti Prenumele Agentului")
        ->setRequired(true);

    $telefon = new Zend_Form_Element_Text("telefon");
    $telefon->setLabel("Telefon:")
        ->setDescription ("Introduceti Telefonul Agentului")
        ->setRequired(true);

    $parola = new Zend_Form_Element_Password("parola");
    $parola->setLabel("Parola:")
        ->setDescription ("Introduceti Parola Agentului")
        ->setRequired(true);

    $poza = new Zend_Form_Element_File("poza");
    $poza->setLabel("Poza Agent:")
        ->setRequired(true)
        ->addValidator('Count', false, 1)
        ->setDestination(APPLICATION_PATH . '/../public/imagini/agenti')
        ->addValidator('Extension', false, 'jpg');

    $submit = new Zend_Form_Element_Submit("adauga");
    $submit->setLabel("Adauga")
        ->setAttrib ( 'class', 'btn btn-primary' )
        ->setIgnore(true);
    $reset = new Zend_Form_Element_Reset ( "reset" );
    $reset->setLabel ( "Reset" )->setAttrib ( 'class', 'btn' );     
    $this->addElements(array($nume, $prenume, $telefon, $parola, $poza, $reset,
    $submit));

    $this->addDisplayGroup ( array ('nume','prenume','telefon','parola','poza'), 'group', array ('legend' => 'Adauga un Agent' ) );
    $this->addDisplayGroup ( array ('adauga', 'reset' ), 'actions', array ('disableLoadDefaultDecorators' => true, 'decorators' => array ('Actions' ) ) );              
}
```

}

**Comment by perfection** [comment]
I have found a fix
In file Twitter/Bootstrap/Form/Decorator/FormElements.php

I added the code below at line 75 

```
        if ($item instanceof Zend_Form_Element_File) {
            $item->setDecorators ( array (

            array ('FieldSize' ), array ('File' ), array ('ElementErrors' ), array ('Description', array ('tag' => 'p', 'class' => 'help-block' ) ), array ('Addon' ), array ('HtmlTag', array ('tag' => 'div', 'class' => 'controls' ) ), array ('Label', array ('class' => 'control-label' ) ), array ('Wrapper' ) )

             );
        }
```

**Comment by perfection** [comment]
Quick update since my IDE reformated the code and I ended up putting the wrong line number,
The snippet should be inserted at line 78
This is how it looks in context

```
        // Check if the element is disabled
        if ($item instanceof Zend_Form_Element && null !== $item->getAttrib('disabled')) {
            $class = $item->getAttrib('class');
            $item->setAttrib('class', $class . ' disabled');
        }
        if ($item instanceof Zend_Form_Element_File) {
            $item->setDecorators ( array (

                    array ('FieldSize' ), array ('File' ), array ('ElementErrors' ), array ('Description', array ('tag' => 'p', 'class' => 'help-block' ) ), array ('Addon' ), array ('HtmlTag', array ('tag' => 'div', 'class' => 'controls' ) ), array ('Label', array ('class' => 'control-label' ) ), array ('Wrapper' ) )

            );
        }
        $items[] = $item->render();
```

**Comment by theUniC** [comment]
The intention of the `Twitter_Bootstrap_Form_Decorator_FormElements` class is to display all the form body accordingly to Twitter's Bootstrap markup, but no to add any extra decorators to the existing elements in the form, before rendering. These decorators should be added elsewhere.

**Comment by perfection** [comment]
My bad, I just found out that that's normal for Zend's Image, Captcha and File elements.

**Comment by theUniC** [comment]
For sure, the invocation is correct. But it's not placed in the right place.

The issue has the origin on the base form class `Twitter_Bootstrap_Form` which is overriding all the decorators in order to set up Twitter Bootstrap's markup properly. The `Zend_Form_Element_File` form element needs at least one decorator that implements the `Zend_Form_Decorator_Marker_File_Interface` to be rendered, but since the decorators are being overriden an Exception is thrown because no decorator is found that implements the interface.

I've added a new element, the file element that checks if at least one decorator that implements the `Zend_Form_Decorator_Marker_File_Interface` has been added. If no one found, it adds the decorator. That should be enough to fix the rendering of the file form element.

In order to set up the file form element properly, you'll have to use the class `Twitter_Bootstrap_Form_Element_File` or the method `addElement` of the `Zend_Form` class (this is the recommended way in order to make use of the internal plugin loaders)

``` php
<?php

class Form_AddAgent extends Twitter_Bootstrap_Form_Horizontal 
{
  public function init ()
  {
    $this->setMethod("post");

    $this->addElement('text', 'nume', array(
      'label'      => 'Nume:',
      'description' => 'Introduceti Numele Agentului',
      'required' => true
    ));

    $this->addElement('text', 'prenume', array(
      'label'      => 'Prenume:',
      'description' => 'Introduceti Prenumele Agentului',
      'required' => true
    ));

    $this->addElement('text', 'telefon', array(
      'label'      => 'Telefon:',
      'description' => 'Introduceti Telefonul Agentului',
      'required' => true
    ));

    $this->addElement('password', 'parola', array(
      'label'      => 'Parola:',
      'description' => 'Introduceti Parola Agentului',
      'required' => true
    ));

    $this->addElement('file', 'poza', array(
      'label'      => 'Poza Agent:',
      'description' => 'Introduceti Telefonul Agentului',
      'required' => true,
      'destination' => APPLICATION_PATH . '/../public/imagini/agenti',
      'validators' => array(/*add your validators*/)
    ));

    $this->addElement('submit', 'adauga', array(
      'label'      => 'Adauga',
      'ignore'    => true,
      'buttonType' => Twitter_Bootstrap_Form_Element_Submit::BUTTON_PRIMARY,
    ));

    // You don't have to add the class "btn", since Twitter_Bootstrap_Form_Element_Submit will
    // handle it for you
    $this->addElement('submit', 'reset', array(
      'label'      => 'Reset'
    ));

    $this->addDisplayGroup(array('nume', 'prenume', 'telefon', 'parola', 'poza'), 'group', array('legend' => 'Adauga un Agent' ));
    $this->addDisplayGroup(array('adauga', 'reset'), 'actions', array('disableLoadDefaultDecorators' => true, 'decorators' => array ('Actions' ) ) );              
  }
}
```

Hope this will help!

**Comment by perfection** [comment]
Thanks, that really helps!

**Comment by jimmykane** [comment]
This is still present in the v3 Of bootstrap

**Comment by jimmykane** [comment]
Any progress on this? Is this acknowledged ?
