### ISSUE TITLE
no Label Decorator in Vertical Form

### ISSUE THREAD

**Issue by dready** [Emagister/zend-form-decorators-bootstrap#65]
Hi there!

is there a specific reason for not adding the Label Decorator to the Vertical Form?

thx

**Comment by twisty** [comment]
Any update on this?

This fix looks good and pretty simple: 25th-floor@d7708c0f16d991a2aa46bdb0c67f4e6cb36946ee

**Comment by dready** [comment]
none, i did not get any update if there was a specific reason why there was no decorator in the first place. i wanted to know if i missed something.

the fix worked in our project without any side effects.

i already forgot about this, since there was no comment i added a pull request just now.

thx

**Comment by theUniC** [comment]
It has been merged! Thanks!
