### ISSUE TITLE
Verical form overwrites horizontal element decorators

### ISSUE THREAD

**Issue by Hagith** [Emagister/zend-form-decorators-bootstrap#7]
Becouse of class inheritance (Horizontal extends Vertical) it's not possible to use horizontal element decorators. They are overwriten in construct via $this->setElementDecorators(). I think that Twitter_Bootstrap_Form_Horizontal should extend Twitter_Bootstrap_Form.

**Comment by theUniC** [comment]
Why you cannot use horizontal element decorators? You should implement the `Zend_Form::init()` method, and add the decorators right there.

Can you provide some example code?

Regards,
Christian.

**Comment by Hagith** [comment]
Hi,

You can find code example in my fork branch: https://github.com/rafalgalka/zend-form-decorators-bootstrap/compare/horizontal-form-issue

I will create pull request addressed to this issue in a minute.

Cheers,
R

**Comment by theUniC** [comment]
OK! Thanks for the PR, I'll check it!

**Comment by theUniC** [comment]
I've checked the code, and I agree with you that `Twitter_Bootstrap_Form_Horizontal`should directly inherit from `Twitter_Bootstrap_Form` class. So I'll merge your PR and refactor some code in order to avoid code repetition. Thanks!

**Comment by Hagith** [comment]
No problem. 

I thank you for this good bootstrap component :)
