### ISSUE TITLE
Required input

### ISSUE THREAD

**Issue by belhauss** [Emagister/zend-form-decorators-bootstrap#94]
Can we make an input field required ? the input is red instead of the default blue color
If yes how, didn't find an example in the documentation, and I'm sorry if this isn't the right place to ask this question ? I'm new here :/

**Comment by theUniC** [comment]
I think I don't understand the question. Zend_Form supports required fields out-of-the-box. And this library wraps the default error classes of twitter bootstrap around the different inputs automatically.

**Comment by belhauss** [comment]
thanks you're right, I had other css that was overrating the bootstrap default behavior.
