### ISSUE TITLE
Add class name to rendered input field div

### ISSUE THREAD

**Issue by imonteiro** [Emagister/zend-form-decorators-bootstrap#95]
Hi,

I'm using Timepicker for Twitter Bootstrap and I need to add a class to input div. Example:

<div class="input-prepend bootstrap-timepicker"><input ..... </div>

It's possible do this in my form file?

Thanks
Ivo

Link:
http://jdewit.github.io/bootstrap-timepicker/

**Comment by theUniC** [comment]
No, currently it is not possible to add any extra class to the input-append/input-prepend div element.
